2 D Numpy Array

In [8]:
import numpy as np

In [5]:
ridership = np.array([
    [   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]
])

In [15]:
# Change False to True for each block of code to see what it does

# Accessing elements
if True:
    print (ridership[1, 3])
    print("")
    print (ridership[1:3, 3:5])
    print("")
    print (ridership[1, :])
    
# Vectorized operations on rows or columns
if True:
    print("")
    print("")
    print (ridership[0, :] + ridership[1, :])
    print (ridership[:, 0] + ridership[:, 1])
    
# Vectorized operations on entire arrays
if True:
    print("")
    print("")
    a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    b = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
    print (a + b)

2328

[[2328 2539]
 [6461 2691]]

[1478 3877 3674 2328 2539]


[1478 3877 3676 2333 2539]
[   0 5355 5701 4952 6410 5509  324    2 5223 5385]


[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [9]:
max_station = np.argmax(ridership, axis =1)

In [13]:
max_station[0]

3

In [11]:
overall_mean = ridership.mean()

In [12]:
overall_mean

2342.5999999999999

In [23]:
mean_for_max = ridership[:, 3].mean()

In [24]:
mean_for_max

3239.9000000000001

In [25]:
def mean_riders_for_max_station(ridership):
    '''
    Fill in this function to find the station with the maximum riders on the
    first day, then return the mean riders per day for that station. Also
    return the mean ridership overall for comparsion.
    
    Hint: NumPy's argmax() function might be useful:
    http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html
    '''
    overall_mean = overall_mean = ridership.mean() # Replace this with your code
    mean_for_max = mean_for_max = ridership[:, 3].mean()# Replace this with your code
    
    return (overall_mean, mean_for_max)

In [26]:
mean_riders_for_max_station(ridership)

(2342.5999999999999, 3239.9000000000001)